import type {
  Caso,
  Delegacia,
  Depoimento,
  Evidencia,
  Investigador,
  Juiz,
  Local,
  Pessoa,
  Suspeito,
  Testemunha,
  Vitima,
} from './types'

function pessoa(
  id: number,
  nome: string,
  genero: string,
  nasc: string,
  descricao: string,
  apelido: string,
): Pessoa {
  return {
    id,
    nome,
    genero,
    cpf: `${100 + id}.${200 + id}.${300 + id}-0${id % 10}`,
    data_nascimento: nasc,
    email: `${nome.toLowerCase().split(' ')[0]}.${id}@correio.jegue.inv`,
    telefone: `(${10 + (id % 80)}) 9${1000 + id}-${2000 + id}`,
    descricao,
    apelido,
  }
}

export const juizes: Juiz[] = [
  {
    id: 1,
    comarca: 'Comarca de Ouro Preto',
    pessoa: pessoa(90, 'Bartolomeu Aguiar', 'Masculino', '1948-03-12', 'Magistrado veterano de casos criminais.', 'O Togado'),
  },
  {
    id: 2,
    comarca: 'Comarca da Sé — São Paulo',
    pessoa: pessoa(91, 'Constança Vilella', 'Feminino', '1955-07-30', 'Juíza titular da vara criminal.', 'A Sentença'),
  },
  {
    id: 3,
    comarca: 'Comarca de Salvador',
    pessoa: pessoa(92, 'Ademar Pinho', 'Masculino', '1951-11-02', 'Especialista em crimes patrimoniais.', 'Dr. Ademar'),
  },
]

export const casos: Caso[] = [
  {
    id: 1,
    numero: '001 — 1988',
    titulo: 'O Roubo da Ourivesaria Delfino',
    descricao:
      'Assalto noturno à tradicional ourivesaria do centro histórico. Peças de ouro e pedras raras desapareceram sem sinais de arrombamento na porta principal.',
    tipo: 'Roubo',
    data_ocorrido: '1988-05-14',
    data_arquivamento: '1991-02-20',
    causa_arquivamento: 'Ausência de novas pistas e prescrição parcial das provas materiais.',
    data_ultima_atualizacao: '2024-09-01',
    observacoes: 'Câmeras da época não registraram o vulto que acionou o cofre.',
    status: 'arquivado',
    juiz: juizes[0],
    cidade: 'Ouro Preto',
    estado: 'MG',
  },
  {
    id: 2,
    numero: '002 — 1996',
    titulo: 'O Desaparecimento da Enseada',
    descricao:
      'Sequestro relâmpago que se tornou desaparecimento prolongado de uma herdeira às margens da enseada. Bilhete de resgate nunca confirmado.',
    tipo: 'Sequestro',
    data_ocorrido: '1996-08-03',
    data_arquivamento: '2000-01-15',
    causa_arquivamento: 'Investigação suspensa após esgotamento das linhas de apuração.',
    data_ultima_atualizacao: '2025-06-12',
    observacoes: 'Reaberto após depoimento anônimo recebido pela agência.',
    status: 'em reabertura',
    juiz: juizes[2],
    cidade: 'Salvador',
    estado: 'BA',
  },
  {
    id: 3,
    numero: '003 — 2003',
    titulo: 'O Incêndio do Armazém Vittoria',
    descricao:
      'Incêndio criminoso que consumiu o armazém de tecidos importados. Perícia apontou uso de acelerante em três focos distintos.',
    tipo: 'Incêndio Criminoso',
    data_ocorrido: '2003-11-27',
    data_arquivamento: null,
    causa_arquivamento: null,
    data_ultima_atualizacao: '2025-11-30',
    observacoes: 'Linha de investigação ativa sobre disputa de seguro.',
    status: 'em andamento',
    juiz: juizes[1],
    cidade: 'São Paulo',
    estado: 'SP',
  },
  {
    id: 4,
    numero: '004 — 1979',
    titulo: 'O Homicídio da Rua das Lanternas',
    descricao:
      'Homicídio noturno de um relojoeiro em seu ateliê. Nenhum objeto de valor foi levado, sugerindo motivação pessoal.',
    tipo: 'Homicídio',
    data_ocorrido: '1979-04-09',
    data_arquivamento: '1984-10-01',
    causa_arquivamento: 'Prescrição e perda de testemunhas-chave.',
    data_ultima_atualizacao: '2023-12-18',
    observacoes: 'Amostra de sangue preservada em arquivo frio.',
    status: 'arquivado',
    juiz: juizes[0],
    cidade: 'Ouro Preto',
    estado: 'MG',
  },
  {
    id: 5,
    numero: '005 — 2011',
    titulo: 'A Fraude do Banco Meridiano',
    descricao:
      'Esquema de desvio de fundos por meio de contas fantasmas ao longo de sete anos. Documentação contábil adulterada.',
    tipo: 'Fraude',
    data_ocorrido: '2011-02-16',
    data_arquivamento: null,
    causa_arquivamento: null,
    data_ultima_atualizacao: '2026-01-08',
    observacoes: 'Caso resolvido após confissão e devolução parcial dos valores.',
    status: 'resolvido',
    juiz: juizes[1],
    cidade: 'São Paulo',
    estado: 'SP',
  },
  {
    id: 6,
    numero: '006 — 1993',
    titulo: 'O Assalto ao Expresso Noturno',
    descricao:
      'Roubo a uma composição ferroviária de carga durante a madrugada. Suspeita de participação interna.',
    tipo: 'Roubo',
    data_ocorrido: '1993-07-21',
    data_arquivamento: '1997-03-30',
    causa_arquivamento: 'Provas insuficientes para indiciamento.',
    data_ultima_atualizacao: '2025-03-22',
    observacoes: 'Digital parcial recuperada de vagão preservada.',
    status: 'em reabertura',
    juiz: juizes[2],
    cidade: 'Curitiba',
    estado: 'PR',
  },
  {
    id: 7,
    numero: '007 — 1985',
    titulo: 'O Sequestro do Solar Amélia',
    descricao:
      'Sequestro de um comerciante em sua residência histórica. Libertado após negociação, autores nunca identificados.',
    tipo: 'Sequestro',
    data_ocorrido: '1985-09-05',
    data_arquivamento: '1989-06-11',
    causa_arquivamento: 'Encerramento por ausência de identificação dos autores.',
    data_ultima_atualizacao: '2024-02-14',
    observacoes: 'Vítima recorda odor de tabaco e voz rouca do captor.',
    status: 'arquivado',
    juiz: juizes[0],
    cidade: 'Salvador',
    estado: 'BA',
  },
  {
    id: 8,
    numero: '008 — 2007',
    titulo: 'O Homicídio do Cais Velho',
    descricao:
      'Corpo encontrado no cais em circunstâncias suspeitas. Perícia forense identificou material genético sob as unhas.',
    tipo: 'Homicídio',
    data_ocorrido: '2007-10-30',
    data_arquivamento: '2012-05-19',
    causa_arquivamento: 'Arquivado por ausência de correspondência genética à época.',
    data_ultima_atualizacao: '2025-10-01',
    observacoes: 'Perfil genético aguarda novo confronto em banco de dados.',
    status: 'arquivado',
    juiz: juizes[2],
    cidade: 'Recife',
    estado: 'PE',
  },
]

export const vitimas: Vitima[] = [
  {
    id: 1,
    caso_id: 1,
    situacao: 'Sobrevivente',
    status: 'Depoente',
    lesao: 'Nenhuma',
    ocupacao: 'Ourives',
    pessoa: pessoa(1, 'Delfino Salgueiro', 'Masculino', '1940-01-20', 'Proprietário da ourivesaria assaltada.', 'Seu Delfino'),
  },
  {
    id: 2,
    caso_id: 2,
    situacao: 'Desaparecida',
    status: 'Não localizada',
    lesao: 'Desconhecida',
    ocupacao: 'Herdeira',
    pessoa: pessoa(2, 'Isaura Menezes', 'Feminino', '1972-04-18', 'Herdeira desaparecida às margens da enseada.', 'Sinhá Isaura'),
  },
  {
    id: 3,
    caso_id: 3,
    situacao: 'Sobrevivente',
    status: 'Testemunhou o fogo',
    lesao: 'Inalação de fumaça',
    ocupacao: 'Comerciante',
    pessoa: pessoa(3, 'Vittorio Bragança', 'Masculino', '1958-09-12', 'Dono do armazém incendiado.', 'Vittorio'),
  },
  {
    id: 4,
    caso_id: 4,
    situacao: 'Falecido',
    status: 'Óbito',
    lesao: 'Ferimento fatal',
    ocupacao: 'Relojoeiro',
    pessoa: pessoa(4, 'Anselmo Torres', 'Masculino', '1930-06-01', 'Relojoeiro assassinado no ateliê.', 'Mestre Anselmo'),
  },
  {
    id: 5,
    caso_id: 5,
    situacao: 'Sobrevivente',
    status: 'Instituição lesada',
    lesao: 'Nenhuma',
    ocupacao: 'Instituição bancária',
    pessoa: pessoa(5, 'Raimundo Fontes', 'Masculino', '1965-12-22', 'Gerente que denunciou a fraude.', 'Raimundo'),
  },
  {
    id: 6,
    caso_id: 6,
    situacao: 'Sobrevivente',
    status: 'Depoente',
    lesao: 'Contusões leves',
    ocupacao: 'Maquinista',
    pessoa: pessoa(6, 'Otávio Bento', 'Masculino', '1955-02-14', 'Maquinista rendido durante o assalto.', 'Seu Otávio'),
  },
  {
    id: 7,
    caso_id: 7,
    situacao: 'Sobrevivente',
    status: 'Libertado',
    lesao: 'Estresse pós-traumático',
    ocupacao: 'Comerciante',
    pessoa: pessoa(7, 'Fernão Queiroz', 'Masculino', '1938-08-19', 'Comerciante sequestrado no solar.', 'Fernão'),
  },
  {
    id: 8,
    caso_id: 8,
    situacao: 'Falecido',
    status: 'Óbito',
    lesao: 'Ferimento fatal',
    ocupacao: 'Estivador',
    pessoa: pessoa(8, 'Jorge Amâncio', 'Masculino', '1969-03-27', 'Estivador encontrado no cais.', 'Jorginho'),
  },
]

export const suspeitos: Suspeito[] = [
  {
    id: 1,
    status: 'Foragido',
    possui_antecedentes: true,
    motivo: 'Ganância / venda de peças raras',
    observacoes: 'Conhecido por atuar em cidades históricas.',
    acusacao: 'Furto qualificado',
    ligacao_crime: 'Reconhecido por vendedor de peças no mercado paralelo.',
    historico_criminal: 'Duas passagens por receptação.',
    casos_ids: [1, 4], // ligado a mais de um caso
    pessoa: pessoa(10, 'Cornélio Vasques', 'Masculino', '1952-05-10', 'Antiquário com ligações no mercado clandestino.', 'O Antiquário'),
  },
  {
    id: 2,
    status: 'Inocentado',
    possui_antecedentes: false,
    motivo: 'Disputa de herança',
    observacoes: 'Álibi confirmado por terceiros.',
    acusacao: 'Cárcere privado',
    ligacao_crime: 'Parentesco com a vítima.',
    historico_criminal: 'Sem antecedentes.',
    casos_ids: [2],
    pessoa: pessoa(11, 'Genoveva Menezes', 'Feminino', '1968-10-04', 'Prima da herdeira desaparecida.', 'Dona Genoveva'),
  },
  {
    id: 3,
    status: 'Indiciado',
    possui_antecedentes: true,
    motivo: 'Fraude de seguro',
    observacoes: 'Movimentações financeiras suspeitas no período do incêndio.',
    acusacao: 'Incêndio doloso',
    ligacao_crime: 'Sócio oculto do armazém.',
    historico_criminal: 'Passagem por estelionato.',
    casos_ids: [3, 5], // ligado a mais de um caso
    pessoa: pessoa(12, 'Lauro Bittencourt', 'Masculino', '1960-01-29', 'Investidor com participação em seguros.', 'Doutor Lauro'),
  },
  {
    id: 4,
    status: 'Detido',
    possui_antecedentes: true,
    motivo: 'Rixa antiga',
    observacoes: 'Material genético em confronto.',
    acusacao: 'Homicídio',
    ligacao_crime: 'Desavença registrada com a vítima.',
    historico_criminal: 'Uma passagem por lesão corporal.',
    casos_ids: [8],
    pessoa: pessoa(13, 'Damião Peçanha', 'Masculino', '1971-07-16', 'Estivador rival da vítima do cais.', 'Damião'),
  },
  {
    id: 5,
    status: 'Foragido',
    possui_antecedentes: true,
    motivo: 'Roubo planejado',
    observacoes: 'Suspeita de participação interna nas ferrovias.',
    acusacao: 'Roubo majorado',
    ligacao_crime: 'Ex-funcionário da companhia ferroviária.',
    historico_criminal: 'Antecedente por furto.',
    casos_ids: [6, 1], // ligado a mais de um caso
    pessoa: pessoa(14, 'Sebastião Vidal', 'Masculino', '1959-11-11', 'Ex-ferroviário desligado por conduta.', 'Bastião'),
  },
  {
    id: 6,
    status: 'Inocentado',
    possui_antecedentes: false,
    motivo: 'Não estabelecido',
    observacoes: 'Liberado por falta de provas.',
    acusacao: 'Sequestro',
    ligacao_crime: 'Presença nas imediações do solar.',
    historico_criminal: 'Sem antecedentes.',
    casos_ids: [7],
    pessoa: pessoa(15, 'Aurélio Campos', 'Masculino', '1950-03-08', 'Vizinho do solar sequestrado.', 'Seu Aurélio'),
  },
]

export const testemunhas: Testemunha[] = [
  {
    id: 1,
    caso_id: 1,
    envolvimento: 'Vigia noturno da praça',
    obs_investigador: 'Relato consistente, porém visão parcial.',
    pessoa: pessoa(20, 'Belmiro Rosa', 'Masculino', '1945-02-02', 'Vigia que ouviu o alarme.', 'Seu Belmiro'),
  },
  {
    id: 2,
    caso_id: 2,
    envolvimento: 'Barqueiro da enseada',
    obs_investigador: 'Viu embarcação suspeita ao amanhecer.',
    pessoa: pessoa(21, 'Nivaldo Mares', 'Masculino', '1963-05-19', 'Barqueiro local.', 'Nivaldo'),
  },
  {
    id: 3,
    caso_id: 3,
    envolvimento: 'Bombeiro voluntário',
    obs_investigador: 'Descreveu os focos múltiplos do incêndio.',
    pessoa: pessoa(22, 'Heitor Salles', 'Masculino', '1974-08-30', 'Primeiro a chegar ao local.', 'Heitor'),
  },
  {
    id: 4,
    caso_id: 4,
    envolvimento: 'Aprendiz do relojoeiro',
    obs_investigador: 'Última pessoa a ver a vítima com vida.',
    pessoa: pessoa(23, 'Emília Nogueira', 'Feminino', '1962-12-07', 'Aprendiz do ateliê.', 'Emília'),
  },
  {
    id: 5,
    caso_id: 8,
    envolvimento: 'Pescador do cais',
    obs_investigador: 'Ouviu discussão na noite do crime.',
    pessoa: pessoa(24, 'Tobias Lemos', 'Masculino', '1970-04-25', 'Pescador que frequentava o cais.', 'Tobias'),
  },
  {
    id: 6,
    caso_id: 6,
    envolvimento: 'Guarda-freios',
    obs_investigador: 'Notou vagão destravado antes do horário.',
    pessoa: pessoa(25, 'Clóvis Pena', 'Masculino', '1957-06-13', 'Guarda-freios do expresso.', 'Clóvis'),
  },
]

export const depoimentos: Depoimento[] = [
  {
    id: 1,
    caso_id: 1,
    pessoa_id: 20,
    papel: 'Testemunha',
    texto: 'Ouvi o alarme por volta das três da madrugada e vi um vulto atravessar a praça em direção ao beco.',
    data: '1988-05-15',
    confiabilidade: 'Media',
    observacoes: 'Visão parcial pela neblina.',
  },
  {
    id: 2,
    caso_id: 2,
    pessoa_id: 21,
    papel: 'Testemunha',
    texto: 'Uma canoa sem lanterna cruzou a enseada ao amanhecer, coisa que jamais vi por aqui.',
    data: '1996-08-04',
    confiabilidade: 'Alta',
    observacoes: 'Detalhes coerentes com a maré daquele dia.',
  },
  {
    id: 3,
    caso_id: 3,
    pessoa_id: 22,
    papel: 'Testemunha',
    texto: 'O fogo nascia em três pontos ao mesmo tempo, algo impossível num incêndio acidental.',
    data: '2003-11-28',
    confiabilidade: 'Alta',
    observacoes: 'Compatível com o laudo pericial.',
  },
  {
    id: 4,
    caso_id: 4,
    pessoa_id: 23,
    papel: 'Testemunha',
    texto: 'O mestre estava agitado naquela tarde e mencionou uma dívida antiga com um velho conhecido.',
    data: '1979-04-10',
    confiabilidade: 'Alta',
    observacoes: 'Depoimento reiterado anos depois.',
  },
  {
    id: 5,
    caso_id: 1,
    pessoa_id: 1,
    papel: 'Vítima',
    texto: 'O cofre foi aberto sem violência, como se conhecessem a combinação.',
    data: '1988-05-16',
    confiabilidade: 'Alta',
    observacoes: 'Sugere participação de alguém próximo.',
  },
  {
    id: 6,
    caso_id: 8,
    pessoa_id: 24,
    papel: 'Testemunha',
    texto: 'Houve uma discussão áspera perto da doca, mas a névoa não deixou ver os rostos.',
    data: '2007-10-31',
    confiabilidade: 'Media',
    observacoes: 'Horário compatível com a perícia.',
  },
  {
    id: 7,
    caso_id: 2,
    pessoa_id: 21,
    papel: 'Testemunha',
    texto: 'Retornei depois de anos para acrescentar que a canoa tinha marcas de uma oficina do cais norte.',
    data: '2025-06-10',
    confiabilidade: 'Alta',
    observacoes: 'Novo detalhe que motivou a reabertura.',
  },
  {
    id: 8,
    caso_id: 6,
    pessoa_id: 25,
    papel: 'Testemunha',
    texto: 'O vagão de carga estava destravado bem antes da parada programada.',
    data: '1993-07-22',
    confiabilidade: 'Media',
    observacoes: 'Indício de participação interna.',
  },
]

export const enderecos = {
  ouroPreto: { id: 1, rua: 'Rua das Lanternas', numero: '45', bairro: 'Centro Histórico', cidade: 'Ouro Preto', estado: 'MG', cep: '35400-000' },
  salvador: { id: 2, rua: 'Ladeira da Enseada', numero: '12', bairro: 'Comércio', cidade: 'Salvador', estado: 'BA', cep: '40015-000' },
  saoPaulo: { id: 3, rua: 'Rua do Gasômetro', numero: '300', bairro: 'Brás', cidade: 'São Paulo', estado: 'SP', cep: '03004-000' },
  curitiba: { id: 4, rua: 'Pátio Ferroviário', numero: 's/n', bairro: 'Rebouças', cidade: 'Curitiba', estado: 'PR', cep: '80230-000' },
  recife: { id: 5, rua: 'Cais Velho', numero: '8', bairro: 'Bairro do Recife', cidade: 'Recife', estado: 'PE', cep: '50030-000' },
}

export const delegacias: Delegacia[] = [
  { id: 1, nome: '1ª Delegacia de Ouro Preto', tipo: 'Crimes Patrimoniais', delegado_responsavel: 'Del. Ubirajara Costa', email_delegado: 'ubirajara@dp.jegue.inv', endereco: enderecos.ouroPreto },
  { id: 2, nome: 'Delegacia Marítima de Salvador', tipo: 'Pessoas Desaparecidas', delegado_responsavel: 'Del. Sônia Andrade', email_delegado: 'sonia@dp.jegue.inv', endereco: enderecos.salvador },
  { id: 3, nome: 'Delegacia Central de São Paulo', tipo: 'Crimes Complexos', delegado_responsavel: 'Del. Ricardo Maia', email_delegado: 'ricardo@dp.jegue.inv', endereco: enderecos.saoPaulo },
  { id: 4, nome: 'Delegacia Ferroviária de Curitiba', tipo: 'Roubos de Carga', delegado_responsavel: 'Del. Íris Tavares', email_delegado: 'iris@dp.jegue.inv', endereco: enderecos.curitiba },
  { id: 5, nome: 'Delegacia Portuária do Recife', tipo: 'Homicídios', delegado_responsavel: 'Del. Fábio Cordeiro', email_delegado: 'fabio@dp.jegue.inv', endereco: enderecos.recife },
]

export const locais: Local[] = [
  { id: 1, caso_id: 1, descricao: 'Ourivesaria Delfino, salão principal e cofre.', fotos: [], endereco: enderecos.ouroPreto },
  { id: 2, caso_id: 2, descricao: 'Margens da enseada e ancoradouro antigo.', fotos: [], endereco: enderecos.salvador },
  { id: 3, caso_id: 3, descricao: 'Armazém Vittoria de tecidos importados.', fotos: [], endereco: enderecos.saoPaulo },
  { id: 4, caso_id: 4, descricao: 'Ateliê de relojoaria na Rua das Lanternas.', fotos: [], endereco: enderecos.ouroPreto },
  { id: 6, caso_id: 6, descricao: 'Pátio ferroviário e vagão de carga nº 14.', fotos: [], endereco: enderecos.curitiba },
  { id: 8, caso_id: 8, descricao: 'Cais Velho, doca norte.', fotos: [], endereco: enderecos.recife },
]

export const evidencias: Evidencia[] = [
  { id: 1, caso_id: 1, delegacia_id: 1, local_id: 1, tipo: 'Objeto', descricao: 'Ferramenta de arrombamento fino encontrada no beco.', data_coleta: '1988-05-15', observacoes: 'Sem digitais aproveitáveis.', analise_forense_disponivel: 'Análise metalográfica concluída. Sem material genético.' },
  { id: 2, caso_id: 1, delegacia_id: 1, local_id: 1, tipo: 'Documento', descricao: 'Registro de vendas com anotação suspeita.', data_coleta: '1988-06-01', observacoes: 'Caligrafia em análise.', analise_forense_disponivel: 'Grafotécnica disponível.' },
  { id: 3, caso_id: 2, delegacia_id: 2, local_id: 2, tipo: 'Fibra', descricao: 'Fragmento de corda de embarcação.', data_coleta: '1996-08-05', observacoes: 'Compatível com oficina do cais.', analise_forense_disponivel: 'Análise de DNA disponível — perfil genético parcial isolado da fibra.' },
  { id: 4, caso_id: 3, delegacia_id: 3, local_id: 3, tipo: 'Química', descricao: 'Resíduo de acelerante em três focos.', data_coleta: '2003-11-28', observacoes: 'Perícia confirmou incêndio doloso.', analise_forense_disponivel: 'Cromatografia disponível. Sem DNA.' },
  { id: 5, caso_id: 4, delegacia_id: 1, local_id: 4, tipo: 'Biológica', descricao: 'Amostra de sangue preservada em arquivo frio.', data_coleta: '1979-04-09', observacoes: 'Preservada para futuro confronto.', analise_forense_disponivel: 'Perfil genético (DNA) disponível para confronto em banco de dados.' },
  { id: 6, caso_id: 5, delegacia_id: 3, local_id: 3, tipo: 'Documento', descricao: 'Planilhas contábeis adulteradas.', data_coleta: '2011-03-02', observacoes: 'Base da acusação de fraude.', analise_forense_disponivel: 'Perícia contábil disponível.' },
  { id: 7, caso_id: 6, delegacia_id: 4, local_id: 6, tipo: 'Impressão digital', descricao: 'Digital parcial em trava de vagão.', data_coleta: '1993-07-22', observacoes: 'Confronto em andamento.', analise_forense_disponivel: 'Datiloscopia disponível.' },
  { id: 8, caso_id: 8, delegacia_id: 5, local_id: 8, tipo: 'Biológica', descricao: 'Material genético sob as unhas da vítima.', data_coleta: '2007-10-30', observacoes: 'Aguardando confronto.', analise_forense_disponivel: 'Análise de DNA disponível — perfil genético completo.' },
  { id: 9, caso_id: 3, delegacia_id: 3, local_id: 3, tipo: 'Objeto', descricao: 'Recipiente de combustível descartado.', data_coleta: '2025-11-20', observacoes: 'Coletado na reinspeção recente.', analise_forense_disponivel: 'Análise de DNA disponível — vestígios em confronto.' },
  { id: 10, caso_id: 8, delegacia_id: 5, local_id: 8, tipo: 'Objeto', descricao: 'Anzol com resíduo têxtil.', data_coleta: '2025-09-15', observacoes: 'Reanálise recente do arquivo.', analise_forense_disponivel: 'Análise têxtil disponível. Sem DNA.' },
]

export const investigadores: Investigador[] = [
  {
    id: 1,
    especialidade: 'Crimes patrimoniais e antiguidades',
    casos_ids: [1, 6],
    pessoa: pessoa(30, 'Aurora Belfort', 'Feminino', '1970-01-15', 'Investigadora-chefe de casos frios.', 'A Lupa'),
  },
  {
    id: 2,
    especialidade: 'Perícia forense e genética',
    casos_ids: [8, 4, 2],
    pessoa: pessoa(31, 'Teodoro Vasconcelos', 'Masculino', '1966-09-09', 'Perito responsável por reanálises de DNA.', 'O Perito'),
  },
  {
    id: 3,
    especialidade: 'Crimes financeiros',
    casos_ids: [5, 3],
    pessoa: pessoa(32, 'Marcela Prado', 'Feminino', '1978-03-21', 'Especialista em fraudes e contabilidade.', 'A Contadora'),
  },
  {
    id: 4,
    especialidade: 'Investigação de campo',
    casos_ids: [7, 2],
    pessoa: pessoa(33, 'Gregório Alencar', 'Masculino', '1962-11-30', 'Investigador de campo veterano.', 'O Rastreador'),
  },
]

// Casos resolvidos por investigador (para relatório de ranking).
export const casosResolvidosPorInvestigador: Record<number, number> = {
  1: 3,
  2: 5,
  3: 4,
  4: 2,
}
